spring:
  application:
    name: users-authentication
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/users?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
jwt:
  config:
    login-url: /auth/login
    type: signed
